export const ARTICLE_VIEW_CONFIGS = {
  disease: {
    pageType: 'disease',
    htmlField: 'sections',
    relocateImage: false,
    supportsCta: false,
    supportsAuthor: false,
    usesLanguageContext: false,
    articleNameFallback: 'this condition',
    recommendedTitleKey: 'recommendedConditions',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.type2Diabetes || 'Type 2 Diabetes', description: langStrings?.type2DiabetesDescription || 'A chronic condition that affects the way your body processes blood sugar', href: `/${language}/diseases-conditions/type-2-diabetes`, slug: 'type-2-diabetes' },
      { title: langStrings?.hypertension || 'Hypertension', description: langStrings?.hypertensionDescription || 'High blood pressure that can lead to serious health problems', href: `/${language}/diseases-conditions/high-blood-pressure`, slug: 'high-blood-pressure' },
      { title: langStrings?.asthma || 'Asthma', description: langStrings?.asthmaDescription || 'A condition in which your airways narrow and swell and may produce extra mucus', href: `/${language}/diseases-conditions/asthma`, slug: 'asthma' },
      { title: langStrings?.arthritis || 'Arthritis', description: langStrings?.arthritisDescription || 'Inflammation of one or more joints, causing pain and stiffness', href: `/${language}/diseases-conditions/arthritis`, slug: 'arthritis' },
      { title: langStrings?.depression || 'Depression', description: langStrings?.depressionDescription || 'A mood disorder that causes persistent feelings of sadness and loss of interest', href: `/${language}/diseases-conditions/depression`, slug: 'depression' },
      { title: langStrings?.heartDisease || 'Heart Disease', description: langStrings?.heartDiseaseDescription || 'A range of conditions that affect your heart', href: `/${language}/diseases-conditions/heart-disease`, slug: 'heart-disease' },
      { title: langStrings?.gerd || 'GERD', description: langStrings?.gerdDescription || 'Chronic acid reflux that can irritate the lining of your esophagus', href: `/${language}/diseases-conditions/gerd`, slug: 'gerd' },
      { title: langStrings?.migraine || 'Migraine', description: langStrings?.migraineDescription || 'A headache that can cause severe throbbing pain or a pulsing sensation', href: `/${language}/diseases-conditions/migraine-headache`, slug: 'migraine-headache' },
    ],
  },

  'mental-health': {
    pageType: 'mental-health',
    htmlField: 'body_html',
    relocateImage: true,
    supportsCta: true,
    supportsAuthor: true,
    usesLanguageContext: true,
    articleNameFallback: 'this topic',
    recommendedTitleKey: 'recommendedTopics',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.depression || 'Depression', description: langStrings?.depressionDescription || '', href: `/${language}/mental-health/depression`, slug: 'depression' },
      { title: langStrings?.anxiety || 'Anxiety', description: langStrings?.anxietyDescription || '', href: `/${language}/mental-health/anxiety`, slug: 'anxiety' },
      { title: langStrings?.ptsd || 'PTSD', description: langStrings?.ptsdDescription || '', href: `/${language}/mental-health/ptsd`, slug: 'ptsd' },
      { title: langStrings?.bipolarDisorder || 'Bipolar Disorder', description: langStrings?.bipolarDisorderDescription || '', href: `/${language}/mental-health/bipolar-disorder`, slug: 'bipolar-disorder' },
      { title: langStrings?.ocd || 'OCD', description: langStrings?.ocdDescription || '', href: `/${language}/mental-health/ocd`, slug: 'ocd' },
      { title: langStrings?.adhd || 'ADHD', description: langStrings?.adhdDescription || '', href: `/${language}/mental-health/adhd`, slug: 'adhd' },
      { title: langStrings?.eatingDisorders || 'Eating Disorders', description: langStrings?.eatingDisordersDescription || '', href: `/${language}/mental-health/eating-disorders`, slug: 'eating-disorders' },
      { title: langStrings?.schizophrenia || 'Schizophrenia', description: langStrings?.schizophreniaDescription || '', href: `/${language}/mental-health/schizophrenia`, slug: 'schizophrenia' },
    ],
  },

  'prevention-wellness': {
    pageType: 'prevention-wellness',
    htmlField: 'body_html',
    relocateImage: true,
    supportsCta: true,
    supportsAuthor: true,
    usesLanguageContext: true,
    articleNameFallback: 'this topic',
    recommendedTitleKey: 'recommendedTopics',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.nutrition || 'Nutrition & Diet', description: langStrings?.nutritionDescription || '', href: `/${language}/prevention-wellness/nutrition`, slug: 'nutrition' },
      { title: langStrings?.exercise || 'Exercise & Fitness', description: langStrings?.exerciseDescription || '', href: `/${language}/prevention-wellness/exercise`, slug: 'exercise' },
      { title: langStrings?.sleepHygiene || 'Sleep Hygiene', description: langStrings?.sleepHygieneDescription || '', href: `/${language}/prevention-wellness/sleep-hygiene`, slug: 'sleep-hygiene' },
      { title: langStrings?.stressManagement || 'Stress Management', description: langStrings?.stressManagementDescription || '', href: `/${language}/prevention-wellness/stress-management`, slug: 'stress-management' },
      { title: langStrings?.vaccinations || 'Vaccinations & Immunization', description: langStrings?.vaccinationsDescription || '', href: `/${language}/prevention-wellness/vaccinations`, slug: 'vaccinations' },
      { title: langStrings?.preventiveScreenings || 'Preventive Screenings', description: langStrings?.preventiveScreeningsDescription || '', href: `/${language}/prevention-wellness/preventive-screenings`, slug: 'preventive-screenings' },
      { title: langStrings?.heartHealth || 'Heart Health', description: langStrings?.heartHealthDescription || '', href: `/${language}/prevention-wellness/heart-health`, slug: 'heart-health' },
      { title: langStrings?.healthyAging || 'Healthy Aging', description: langStrings?.healthyAgingDescription || '', href: `/${language}/prevention-wellness/healthy-aging`, slug: 'healthy-aging' },
    ],
  },

  articles: {
    pageType: 'articles',
    htmlField: 'body_html',
    relocateImage: true,
    supportsCta: true,
    supportsAuthor: false,
    usesLanguageContext: true,
    articleNameFallback: 'this article',
    recommendedTitleKey: null,
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: () => [],
  },

  medication: {
    pageType: 'medication',
    htmlField: 'body_html',
    relocateImage: false,
    supportsCta: false,
    supportsAuthor: false,
    usesLanguageContext: false,
    articleNameFallback: 'this medication',
    recommendedTitleKey: 'recommendedMedications',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.lisinopril || 'Lisinopril', description: langStrings?.lisinoprilDescription || 'An ACE inhibitor used to treat high blood pressure and heart failure', href: `/${language}/medications/lisinopril`, slug: 'lisinopril' },
      { title: langStrings?.metformin || 'Metformin', description: langStrings?.metforminDescription || 'A first-line medication for the treatment of type 2 diabetes', href: `/${language}/medications/metformin`, slug: 'metformin' },
      { title: langStrings?.vitaminD || 'Vitamin D', description: langStrings?.vitaminDDescription || 'An essential nutrient that helps your body absorb calcium', href: `/${language}/medications/vitamin-d`, slug: 'vitamin-d' },
      { title: langStrings?.omeprazole || 'Omeprazole', description: langStrings?.omeprazoleDescription || 'A proton pump inhibitor used to treat GERD and stomach ulcers', href: `/${language}/medications/omeprazole`, slug: 'omeprazole' },
      { title: langStrings?.fishOil || 'Fish Oil', description: langStrings?.fishOilDescription || 'An omega-3 fatty acid supplement that supports heart health', href: `/${language}/medications/fish-oil`, slug: 'fish-oil' },
      { title: langStrings?.atorvastatin || 'Atorvastatin', description: langStrings?.atorvastatinDescription || 'A statin medication used to lower cholesterol levels', href: `/${language}/medications/atorvastatin`, slug: 'atorvastatin' },
      { title: langStrings?.aspirin || 'Aspirin', description: langStrings?.aspirinDescription || 'A common pain reliever and anti-inflammatory medication', href: `/${language}/medications/aspirin`, slug: 'aspirin' },
      { title: langStrings?.sertraline || 'Sertraline', description: langStrings?.sertralineDescription || 'An SSRI antidepressant used to treat depression and anxiety', href: `/${language}/medications/sertraline`, slug: 'sertraline' },
    ],
  },

  symptom: {
    pageType: 'symptom',
    htmlField: 'body_html',
    relocateImage: false,
    supportsCta: false,
    supportsAuthor: false,
    usesLanguageContext: false,
    articleNameFallback: 'this symptom',
    recommendedTitleKey: 'recommendedSymptoms',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.cough || 'Cough', description: langStrings?.coughDescription || 'A reflex action to clear your airways of mucus and irritants', href: `/${language}/symptoms/cough`, slug: 'cough' },
      { title: langStrings?.headache || 'Headache', description: langStrings?.headacheDescription || 'Pain in any region of the head that may be sharp, throbbing, or dull', href: `/${language}/symptoms/headache`, slug: 'headache' },
      { title: langStrings?.fatigue || 'Fatigue', description: langStrings?.fatigueDescription || 'An overall feeling of tiredness or lack of energy', href: `/${language}/symptoms/fatigue`, slug: 'fatigue' },
      { title: langStrings?.abdominalPain || 'Abdominal Pain', description: langStrings?.abdominalPainDescription || 'Pain that occurs between the chest and pelvic regions', href: `/${language}/symptoms/abdominal-pain`, slug: 'abdominal-pain' },
      { title: langStrings?.dizziness || 'Dizziness', description: langStrings?.dizzinessDescription || 'A term used to describe a range of sensations including feeling faint or lightheaded', href: `/${language}/symptoms/dizziness`, slug: 'dizziness' },
      { title: langStrings?.backPain || 'Back Pain', description: langStrings?.backPainDescription || 'Pain felt in the back that usually originates from muscles, nerves, or bones', href: `/${language}/symptoms/back-pain`, slug: 'back-pain' },
      { title: langStrings?.nausea || 'Nausea', description: langStrings?.nauseaDescription || 'An uneasy sensation in the stomach that often comes before vomiting', href: `/${language}/symptoms/nausea`, slug: 'nausea' },
      { title: langStrings?.shortnessOfBreath || 'Shortness of Breath', description: langStrings?.shortnessOfBreathDescription || 'A feeling of not being able to get enough air', href: `/${language}/symptoms/shortness-of-breath`, slug: 'shortness-of-breath' },
    ],
  },

  'test-procedure': {
    pageType: 'test-procedure',
    htmlField: 'body_html',
    relocateImage: false,
    supportsCta: false,
    supportsAuthor: false,
    usesLanguageContext: false,
    articleNameFallback: 'this test',
    recommendedTitleKey: 'recommendedTests',
    recommendedTitleFallback: 'Recommended Topics',
    getRecommendedTopics: (language, langStrings) => [
      { title: langStrings?.cbc || 'Complete Blood Count (CBC)', description: langStrings?.cbcDescription || 'A common blood test that evaluates your overall health', href: `/${language}/tests-procedures/cbc-complete-blood-count`, slug: 'cbc-complete-blood-count' },
      { title: langStrings?.endoscopy || 'Endoscopy', description: langStrings?.endoscopyDescription || 'A procedure to examine the digestive tract using a camera', href: `/${language}/tests-procedures/endoscopy`, slug: 'endoscopy' },
      { title: langStrings?.mri || 'MRI', description: langStrings?.mriDescription || 'A medical imaging technique using magnetic fields and radio waves', href: `/${language}/tests-procedures/mri`, slug: 'mri' },
      { title: langStrings?.ctScan || 'CT Scan', description: langStrings?.ctScanDescription || 'A diagnostic imaging procedure using X-rays to create cross-sectional images', href: `/${language}/tests-procedures/ct-scan`, slug: 'ct-scan' },
      { title: langStrings?.colonoscopy || 'Colonoscopy', description: langStrings?.colonoscopyDescription || 'An exam to detect changes or abnormalities in the large intestine', href: `/${language}/tests-procedures/colonoscopy`, slug: 'colonoscopy' },
      { title: langStrings?.echocardiogram || 'Echocardiogram', description: langStrings?.echocardiogramDescription || 'An ultrasound test that shows how your heart is functioning', href: `/${language}/tests-procedures/echocardiogram`, slug: 'echocardiogram' },
      { title: langStrings?.stressTest || 'Stress Test', description: langStrings?.stressTestDescription || 'A test that measures how well your heart works during physical activity', href: `/${language}/tests-procedures/cardiac-stress-test`, slug: 'cardiac-stress-test' },
      { title: langStrings?.mammogram || 'Mammogram', description: langStrings?.mammogramDescription || 'An X-ray picture of the breast used to look for early signs of breast cancer', href: `/${language}/tests-procedures/mammogram`, slug: 'mammogram' },
    ],
  },
};
