/**
 * Shared article body typography styles for all library view pages.
 * Used by DetailViewClient, BlogViewClient, SymptomViewClient, MedicationViewClient, TestProcedureClient.
 */
export const articleBodySx = {
  fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
  color: "#2a2a2a",
  "& > :first-child": { marginTop: 0 },
  "& div > :first-child": { marginTop: 0 },
  "& img": {
    maxWidth: "100%",
    height: "auto",
    borderRadius: "8px",
    display: "block",
    margin: "2rem auto",
  },
  "& table": {
    width: "100%",
    tableLayout: "fixed",
    borderCollapse: "collapse",
    marginBottom: "2rem",
    fontSize: { xs: "0.85rem", sm: "0.95rem" },
    wordWrap: "break-word",
    "& th, & td": {
      border: "1px solid #e8e8e8",
      padding: { xs: "8px 10px", sm: "12px 16px" },
      textAlign: "left",
      lineHeight: 1.5,
      verticalAlign: "top",
      overflowWrap: "break-word",
    },
    "& th": {
      backgroundColor: "#f4f5f5",
      fontWeight: 600,
      color: "#1a1a1a",
    },
    "& tr:nth-of-type(even) td": {
      backgroundColor: "#fafbfa",
    },
  },
  "& p": {
    marginBottom: "1.25rem",
    lineHeight: 1.8,
    fontSize: "1.05rem",
    color: "#4e5553",
  },
  "& h1": {
    fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
    marginTop: "2.5rem",
    marginBottom: "1rem",
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1a1a1a",
    lineHeight: 1.2,
  },
  "& h2": {
    fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
    marginTop: "2.5rem",
    marginBottom: "0.75rem",
    fontSize: "1.65rem",
    fontWeight: 700,
    color: "#1a1a1a",
    lineHeight: 1.25,
    letterSpacing: "-0.01em",
    paddingTop: "1.5rem",
    borderTop: "1px solid #E8EAE8",
  },
  "& h3": {
    fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
    marginTop: "2rem",
    marginBottom: "0.5rem",
    fontSize: "1.35rem",
    fontWeight: 600,
    color: "#1a1a1a",
    lineHeight: 1.3,
  },
  "& h4": {
    fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
    marginTop: "1.5rem",
    marginBottom: "0.5rem",
    fontSize: "1.15rem",
    fontWeight: 700,
    color: "#1a1a1a",
    letterSpacing: "0.01em",
  },
  "& ul, & ol": {
    marginBottom: "1.25rem",
    paddingLeft: "1.5rem",
    "& li": {
      marginBottom: "0.6rem",
      lineHeight: 1.8,
      fontSize: "1.05rem",
      color: "#4e5553",
    },
  },
  "& ul": {
    listStyle: "disc",
  },
  "& a": {
    color: "#206E55",
    textDecoration: "underline",
    textDecorationColor: "rgba(32, 110, 85, 0.3)",
    textUnderlineOffset: "3px",
    "&:hover": {
      textDecorationColor: "#206E55",
    },
  },
  "& blockquote": {
    borderLeft: "3px solid #206E55",
    paddingLeft: "1.25rem",
    paddingRight: "1.25rem",
    paddingTop: "0.75rem",
    paddingBottom: "0.75rem",
    backgroundColor: "#f4f5f5",
    borderRadius: "0 8px 8px 0",
    color: "#4e5553",
    fontStyle: "italic",
    margin: "1.5rem 0",
    lineHeight: 1.7,
    "& p": {
      marginBottom: "0.5rem",
      "&:last-child": {
        marginBottom: 0,
      },
    },
  },
  "& .tldr-label": {
    color: "#206E55 !important",
    fontSize: "1.3rem",
    fontWeight: 900,
    letterSpacing: "0.02em",
  },
  "& code": {
    backgroundColor: "#f8f8f6",
    padding: "0.2em 0.4em",
    borderRadius: "4px",
    fontFamily: "monospace",
    fontSize: "0.9em",
  },
  "& pre": {
    backgroundColor: "#f8f8f6",
    padding: "1.25rem",
    borderRadius: "8px",
    overflowX: "auto",
    fontFamily: "monospace",
    fontSize: "0.9em",
    marginBottom: "1.5rem",
    border: "1px solid #e8e8e8",
  },
  "& strong": {
    fontWeight: 700,
    color: "#1a1a1a",
  },
  "& em": {
    fontStyle: "italic",
  },
  "& hr": {
    border: 0,
    borderTop: "1px solid #e8e8e8",
    margin: "2.5rem 0",
  },
  "& figure": {
    margin: "2rem auto",
    textAlign: "center",
  },
  "& figcaption": {
    fontFamily: "var(--font-manrope), 'Manrope', sans-serif",
    fontSize: "0.85rem",
    color: "#888",
    marginTop: "0.75rem",
    fontWeight: 500,
  },
  "& iframe": {
    maxWidth: "100%",
    display: "block",
    margin: "2rem auto",
    borderRadius: "8px",
  },
};
