import { useCallback, useRef, type RefObject } from "react";
import { trackToolEvent } from "@/app/utils/analytics";

interface UseDownloadResultOptions {
  toolId: string;
  filename: string;
  heading: string;
  subtitle: string;
  toolName: string;
  target?: string;
  maxPageHeight?: number;
}

interface UseDownloadResultReturn {
  resultRef: RefObject<HTMLDivElement | null>;
  handleDownload: () => Promise<void>;
}

const CAPTURE_PADDING = 24;
const CAPTURE_PADDING_X = 86;
const DEFAULT_MAX_PAGE_HEIGHT = 1250;
const PAGE_BREAK_GUTTER = 40;
const CAPTURE_PAGE_WIDTH = 720;

function sanitize(name: string): string {
  return name.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "report";
}

function buildHeaderElement(
  title: string,
  subtitle: string,
  toolName: string,
  url: string | null,
): {
  element: HTMLDivElement;
  toolNameLink: HTMLAnchorElement | null;
  logoImage: HTMLImageElement;
} {
  const el = document.createElement("div");
  el.style.background = "#206E55";
  el.style.color = "#ffffff";
  el.style.padding = "22px 22px";
  el.style.borderRadius = "0";
  el.style.display = "flex";
  el.style.flexDirection = "column";
  el.style.gap = "28px";
  el.style.textAlign = "left";
  el.style.marginTop = `-${CAPTURE_PADDING}px`;
  el.style.marginLeft = `-${CAPTURE_PADDING_X}px`;
  el.style.marginRight = `-${CAPTURE_PADDING_X}px`;
  el.style.marginBottom = "20px";

  const titleRow = document.createElement("div");
  titleRow.style.display = "flex";
  titleRow.style.alignItems = "center";
  titleRow.style.gap = "14px";

  const logoImage = document.createElement("img");
  logoImage.src = "/icons/icon-192x192.png";
  logoImage.alt = "August";
  logoImage.style.width = "44px";
  logoImage.style.height = "44px";
  logoImage.style.borderRadius = "8px";
  logoImage.style.display = "block";
  logoImage.style.flexShrink = "0";
  titleRow.appendChild(logoImage);

  const titleBlock = document.createElement("div");
  titleBlock.style.display = "flex";
  titleBlock.style.flexDirection = "column";
  titleBlock.style.gap = "2px";

  const titleEl = document.createElement("div");
  titleEl.textContent = title;
  titleEl.style.fontSize = "22px";
  titleEl.style.fontWeight = "500";
  titleEl.style.letterSpacing = "-0.01em";
  titleEl.style.lineHeight = "1.2";
  titleBlock.appendChild(titleEl);

  const subtitleEl = document.createElement("div");
  subtitleEl.textContent = subtitle;
  subtitleEl.style.fontSize = "14px";
  subtitleEl.style.fontWeight = "400";
  subtitleEl.style.color = "rgba(255,255,255,0.78)";
  subtitleEl.style.letterSpacing = "-0.01em";
  subtitleEl.style.lineHeight = "1.2";
  titleBlock.appendChild(subtitleEl);  
  titleRow.appendChild(titleBlock);
  el.appendChild(titleRow);

  const todayLabel = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const generatedLine = document.createElement("div");
  generatedLine.style.fontSize = "13px";
  generatedLine.style.color = "rgba(255,255,255,0.85)";
  generatedLine.style.letterSpacing = "-0.01em";
  generatedLine.style.lineHeight = "1.2";
  generatedLine.appendChild(document.createTextNode("Generated by "));
  generatedLine.style.alignSelf = "flex-end";
  generatedLine.style.textAlign = "right";
  
  let toolNameLink: HTMLAnchorElement | null = null;
  if (url) {
    toolNameLink = document.createElement("a");
    toolNameLink.href = url;
    toolNameLink.textContent = toolName;
    toolNameLink.style.color = "#ffffff";
    toolNameLink.style.fontWeight = "600";
    toolNameLink.style.textDecoration = "underline";
    generatedLine.appendChild(toolNameLink);
  } else {
    generatedLine.appendChild(document.createTextNode(toolName));
  }

  generatedLine.appendChild(document.createTextNode(` on ${todayLabel}`));
  el.appendChild(generatedLine);

  return { element: el, toolNameLink, logoImage };
}

function buildFooterElement(): { element: HTMLDivElement; qrImage: HTMLImageElement } {
  const wrap = document.createElement("div");
  wrap.style.background = "#0d3b29";
  wrap.style.color = "#ffffff";
  wrap.style.borderRadius = "0";
  wrap.style.marginTop = "24px";
  wrap.style.marginLeft = `-${CAPTURE_PADDING_X}px`;
  wrap.style.marginRight = `-${CAPTURE_PADDING_X}px`;
  wrap.style.marginBottom = `-${CAPTURE_PADDING}px`;

  const cta = document.createElement("div");
  cta.style.display = "flex";
  cta.style.justifyContent = "space-between";
  cta.style.alignItems = "center";
  cta.style.padding = "28px 32px 32px";

  const brand = document.createElement("span");
  brand.textContent = "august";
  brand.style.fontSize = "16px";
  brand.style.fontWeight = "400";
  brand.style.color = "rgba(255,255,255,0.85)";
  brand.style.letterSpacing = "-0.01em";
  cta.appendChild(brand);

  const banner = document.createElement("div");
  banner.style.display = "flex";
  banner.style.alignItems = "center";
  banner.style.justifyContent = "center";
  banner.style.gap = "14px";
  banner.style.padding = "12px 18px";
  banner.style.background = "rgba(255,255,255,0.04)";
  banner.style.border = "1px solid rgba(255,255,255,0.12)";
  banner.style.borderRadius = "8px";
  banner.style.boxSizing = "border-box";

  const qrImage = document.createElement("img");
  qrImage.src = "/qr-download-august.png";
  qrImage.alt = "QR code to download August";
  qrImage.style.width = "52px";
  qrImage.style.height = "52px";
  qrImage.style.borderRadius = "4px";
  qrImage.style.display = "block";

  const ctaText = document.createElement("span");
  ctaText.textContent = "Download\naugust";
  ctaText.style.color = "#ffffff";
  ctaText.style.fontFamily = "var(--font-manrope), 'Manrope', sans-serif";
  ctaText.style.fontSize = "1rem";
  ctaText.style.fontWeight = "400";
  ctaText.style.lineHeight = "1.3";
  ctaText.style.whiteSpace = "pre-line";
  ctaText.style.textAlign = "center";

  banner.appendChild(qrImage);
  banner.appendChild(ctaText);
  cta.appendChild(banner);

  wrap.appendChild(cta);

  return { element: wrap, qrImage };
}

export function useDownloadResult({
  toolId,
  filename,
  heading,
  subtitle,
  toolName,
  target = "download_report",
  maxPageHeight = DEFAULT_MAX_PAGE_HEIGHT,
}: UseDownloadResultOptions): UseDownloadResultReturn {
  const resultRef = useRef<HTMLDivElement>(null);

  const handleDownload = useCallback(async () => {
    if (!resultRef.current) return;
    const node = resultRef.current;
    const pageUrl = typeof window !== "undefined" ? window.location.href : null;
    const { element: headerEl, toolNameLink, logoImage } = buildHeaderElement(heading, subtitle, toolName, pageUrl);
    const { element: footerEl, qrImage } = buildFooterElement();

    const pageBg =
      getComputedStyle(document.body).backgroundColor || "#FAF9F5";
    const overlay = document.createElement("div");
    overlay.setAttribute("aria-hidden", "true");
    overlay.style.position = "fixed";
    overlay.style.top = "0";
    overlay.style.left = "0";
    overlay.style.right = "0";
    overlay.style.bottom = "0";
    overlay.style.background = pageBg;
    overlay.style.zIndex = "2147483646";
    overlay.style.pointerEvents = "none";

    const skipEls = Array.from(
      node.querySelectorAll<HTMLElement>('[data-skip-screenshot="true"]'),
    );
    const prevSkipDisplays = skipEls.map((el) => el.style.display);
    skipEls.forEach((el) => {
      el.style.display = "none";
    });
    document.body.appendChild(overlay);
    node.insertBefore(headerEl, node.firstChild);
    node.appendChild(footerEl);
    const prevPadding = node.style.padding;
    const prevBorderRadius = node.style.borderRadius;
    const prevOverflow = node.style.overflow;
    const prevMarginLeft = node.style.marginLeft;
    const prevMarginRight = node.style.marginRight;
    const prevPosition = node.style.position;
    const prevTop = node.style.top;
    const prevLeft = node.style.left;
    const prevWidth = node.style.width;
    const prevMaxWidth = node.style.maxWidth;
    const prevBoxSizing = node.style.boxSizing;
    node.style.padding = `${CAPTURE_PADDING}px ${CAPTURE_PADDING_X}px`;
    node.style.borderRadius = "0";
    node.style.overflow = "visible";
    node.style.marginLeft = "0";
    node.style.marginRight = "0";
    node.style.position = "fixed";
    node.style.top = "0";
    node.style.left = "0";
    node.style.width = `${CAPTURE_PAGE_WIDTH}px`;
    node.style.maxWidth = "none";
    node.style.boxSizing = "border-box";
    const spacerEls: HTMLDivElement[] = [];
    try {
      await Promise.all(
        [qrImage, logoImage].map(
          (img) =>
            new Promise<void>((resolve) => {
              if (img.complete) return resolve();
              img.onload = () => resolve();
              img.onerror = () => resolve();
            }),
        ),
      );
      const nodeRectInit = node.getBoundingClientRect();
      const pageWidth = CAPTURE_PAGE_WIDTH;
      const initialHeight = nodeRectInit.height;
      const isMultiPage = initialHeight > maxPageHeight;
      const contentEdgePage = maxPageHeight - PAGE_BREAK_GUTTER;
      const contentMidPage = maxPageHeight - 2 * PAGE_BREAK_GUTTER;
      let numPagesPlanned = 1;
      if (isMultiPage) {
        const overflow = initialHeight - contentEdgePage;
        const middlePagesNeeded = Math.max(0, Math.ceil((overflow - contentEdgePage) / contentMidPage));
        numPagesPlanned = 2 + middlePagesNeeded;
        const targetTotalHeight =
          2 * contentEdgePage + (numPagesPlanned - 2) * contentMidPage;
        const need = targetTotalHeight - initialHeight;
        if (need > 0) {
          const s = document.createElement("div");
          s.style.height = `${need}px`;
          s.style.flexShrink = "0";
          s.style.background = "#ffffff";
          node.insertBefore(s, footerEl);
          spacerEls.push(s);
        }
      }
      const [{ toJpeg }, { default: jsPDF }] = await Promise.all([
        import("html-to-image"),
        import("jspdf"),
      ]);
      const dataUrl = await toJpeg(node, {
        cacheBust: true,
        pixelRatio: 1.5,
        quality: 0.93,
        backgroundColor: "#ffffff",
        filter: (n) => !(n instanceof HTMLElement) || n.dataset.skipScreenshot !== "true",
      });
      const totalHeight = node.getBoundingClientRect().height;
      const pageHeight = isMultiPage ? maxPageHeight : totalHeight;
      const numPages = numPagesPlanned;
      const pdf = new jsPDF({
        orientation: pageHeight >= pageWidth ? "portrait" : "landscape",
        unit: "px",
        format: [pageWidth, pageHeight],
        hotfixes: ["px_scaling"],
        compress: true,
      });
      for (let i = 0; i < numPages; i++) {
        if (i > 0) pdf.addPage([pageWidth, pageHeight], "portrait");
        if (isMultiPage) {
          const isFirstPage = i === 0;
          const isLastPage = i === numPages - 1;
          const imageStartForPage =
            isFirstPage ? 0 : contentEdgePage + (i - 1) * contentMidPage;
          const pageStartY = isFirstPage ? 0 : PAGE_BREAK_GUTTER;
          pdf.addImage(
            dataUrl,
            "JPEG",
            0,
            pageStartY - imageStartForPage,
            pageWidth,
            totalHeight,
            undefined,
            "FAST",
          );
          pdf.setFillColor(255, 255, 255);
          if (!isFirstPage) {
            pdf.rect(0, 0, pageWidth, PAGE_BREAK_GUTTER, "F");
          }
          if (!isLastPage) {
            pdf.rect(0, pageHeight - PAGE_BREAK_GUTTER, pageWidth, PAGE_BREAK_GUTTER, "F");
          }
        } else {
          pdf.addImage(dataUrl, "JPEG", 0, 0, pageWidth, totalHeight, undefined, "FAST");
        }
      }
      if (toolNameLink && pageUrl) {
        pdf.setPage(1);
        const nodeRect = node.getBoundingClientRect();
        const linkRect = toolNameLink.getBoundingClientRect();
        const linkX = linkRect.left - nodeRect.left;
        const linkY = linkRect.top - nodeRect.top;
        pdf.link(linkX, linkY, linkRect.width, linkRect.height, { url: pageUrl });
      }
      pdf.save(`${sanitize(filename)}.pdf`);
      trackToolEvent(toolId, "cta_clicked", { target });
    } catch {
    } finally {
      node.style.padding = prevPadding;
      node.style.borderRadius = prevBorderRadius;
      node.style.overflow = prevOverflow;
      node.style.marginLeft = prevMarginLeft;
      node.style.marginRight = prevMarginRight;
      node.style.position = prevPosition;
      node.style.top = prevTop;
      node.style.left = prevLeft;
      node.style.width = prevWidth;
      node.style.maxWidth = prevMaxWidth;
      node.style.boxSizing = prevBoxSizing;
      skipEls.forEach((el, i) => {
        el.style.display = prevSkipDisplays[i];
      });
      for (const s of spacerEls) {
        if (s.parentNode === node) node.removeChild(s);
      }
      if (headerEl.parentNode === node) {
        node.removeChild(headerEl);
      }
      if (footerEl.parentNode === node) {
        node.removeChild(footerEl);
      }
      if (overlay.parentNode) {
        overlay.parentNode.removeChild(overlay);
      }
    }
  }, [toolId, filename, heading, subtitle, toolName, target, maxPageHeight]);

  return { resultRef, handleDownload };
}
